version: "3.8"
services: 
    db:
        image: "mysql:5.7"
        environment:
            MYSQL_ROOT_PASSWORD: "myawesomepassword"
        volumes:
            - dbdata:/var/lib/mysql
    interface:
        image: "adminer"
        ports:
            - "8080:8080"
    app:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        environment:
            FLASK_ENV: development
volumes:
    dbdata: